USE IV
GO

--EJEMPLOS DEL CRUD
INSERT INTO EMPLEADO (  NOMBRE, APELLIDOS, FECHA_DE_NACIMIENTO, TELEFONO, EMAIL, SALARIO, ID_CARGO) VALUES
(  'THEYLOR', 'RAMIREZ', '2003-07-23', '942923394', 'theylor.ramirez@gmail.com', 2500.00, 1),
(  'VANIA', 'TORRES', '2005-08-15', '999222444', 'vania.torres@gmail.com', 1800.00, 2),
(  'CARLA', 'PORTAL', '2003-12-20', '111222333', 'carla.portal@gmail.com', 1600.00, 3)

GO

SELECT *
FROM EMPLEADO
GO

SELECT*
FROM PRODUCTO
WHERE PRECIO_UNITARIO >= 50
GO

DELETE
FROM EMPLEADO
WHERE NOMBRE = 'VANIA'
GO
--MOSTRAMOS LA TABLA PARA VERIFICAR EL REGISTRO ELIMINADO
SELECT*
FROM EMPLEADO
GO
--ACTUALIZAMOS EL TELEFONO DEL REGISTRO CON ID 3
UPDATE EMPLEADO 
SET TELEFONO = 123456789
WHERE ID_EMPLEADO = 3
GO
--MOSTRAMOS LA TABLA PARA VERIFICAR EL REGISTRO.
SELECT*
FROM EMPLEADO
GO

--EJEMPLOS DE INNER JOIN
SELECT e.ID_EMPLEADO, e.NOMBRE, e.APELLIDOS, c.DESCRIPCION AS CARGO
FROM EMPLEADO e
INNER JOIN CARGO c
ON e.ID_CARGO = c.ID_CARGO
GO

SELECT p.ID_PRODUCTO, p.NOMBRE_PRODUCTO, c.NOMBRE_CATEGORIA
FROM PRODUCTO p
INNER JOIN CATEGORIA c
ON p.ID_CATEGORIA = c.ID_CATEGORIA
GO

SELECT e.ID_EMPLEADO AS NUMERO, e.NOMBRE AS EMPLEADO_NOMBRE, c.ID_CLIENTE, c.NOMBRE AS CLIENTE_NOMBRE
FROM EMPLEADO e
INNER JOIN CLIENTE c
ON e.APELLIDOS = c.APELLIDOS
GO

SELECT*
FROM CLIENTE
WHERE ID_CLIENTE = 4
GO

SELECT*
FROM EMPLEADO
WHERE ID_EMPLEADO = 1
GO

--PARA CAMBIAR EL APELLIDO DEL CLIENTE CON ID 4
UPDATE CLIENTE 
SET APELLIDOS = 'Vasquez' 
WHERE ID_CLIENTE = 4
GO
--PARA CAMBIAR EL CORREO.
UPDATE CLIENTE 
SET EMAIL = 'ana.vasquez@gmail.com' 
WHERE ID_CLIENTE = 4
GO

--INNER JOIN QUE MUESTRA EL NOMBRE DE LA CATEGORIA Y EL NOMBRE DEL PRODUCTO QUE LO CORRESPONDE
SELECT p.NOMBRE_PRODUCTO, c.NOMBRE_CATEGORIA
FROM PRODUCTO p
INNER JOIN CATEGORIA c
ON p.ID_CATEGORIA = c.ID_CATEGORIA
GO

SELECT e.ID_EMPLEADO, e.NOMBRE, c.DESCRIPCION AS CARGO
FROM EMPLEADO e
INNER JOIN CARGO c
ON e.ID_CARGO = c.ID_CARGO
GO

-- 5 EJEMPLOS DE LEFT JOIN

SELECT e.ID_EMPLEADO, e.NOMBRE, c.DESCRIPCION AS CARGO
FROM EMPLEADO e
LEFT JOIN CARGO c
ON e.ID_CARGO = c.ID_CARGO
GO

SELECT p.ID_PRODUCTO, p.NOMBRE_PRODUCTO, c.NOMBRE_CATEGORIA
FROM PRODUCTO p
LEFT JOIN CATEGORIA c
ON p.ID_CATEGORIA = c.ID_CATEGORIA
GO

SELECT cl.ID_CLIENTE, cl.NOMBRE, cl.HISTORIAL_COMPRA, cat.NOMBRE_CATEGORIA
FROM CLIENTE cl
LEFT JOIN CATEGORIA cat
ON cl.HISTORIAL_COMPRA = cat.NOMBRE_CATEGORIA
GO

SELECT c.ID_CARGO, c.DESCRIPCION AS CARGO, e.NOMBRE AS EMPLEADO , e.TELEFONO AS [NUMERO DE CELULAR] 
FROM CARGO c
LEFT JOIN EMPLEADO e
ON c.ID_CARGO = e.ID_CARGO;
GO

SELECT cat.ID_CATEGORIA, cat.NOMBRE_CATEGORIA, p.NOMBRE_PRODUCTO, p.ESTADO
FROM CATEGORIA cat
LEFT JOIN PRODUCTO p
ON cat.ID_CATEGORIA = p.ID_CATEGORIA
WHERE p.ESTADO IS NULL OR p.ESTADO = 'Agotado'
GO

-- 5 EJEMPLOS DE RIGHT JOIN
SELECT c.ID_CARGO, c.DESCRIPCION AS CARGO, e.NOMBRE AS EMPLEADO
FROM EMPLEADO e
RIGHT JOIN CARGO c
ON e.ID_CARGO = c.ID_CARGO
GO

SELECT p.ID_PRODUCTO, p.NOMBRE_PRODUCTO, c.NOMBRE_CATEGORIA
FROM PRODUCTO p
RIGHT JOIN CATEGORIA c
ON p.ID_CATEGORIA = c.ID_CATEGORIA
GO

SELECT cl.ID_CLIENTE, cl.NOMBRE AS CLIENTE, cat.NOMBRE_CATEGORIA
FROM CLIENTE cl
RIGHT JOIN CATEGORIA cat
ON cl.HISTORIAL_COMPRA = cat.NOMBRE_CATEGORIA
GO

SELECT p.ID_PRODUCTO, p.NOMBRE_PRODUCTO, c.ID_CATEGORIA, c.NOMBRE_CATEGORIA
FROM PRODUCTO p
RIGHT JOIN CATEGORIA c
ON p.DESCRIPCION = c.DESCRIPCION
GO

SELECT c.ID_CARGO, c.DESCRIPCION AS CARGO, e.NOMBRE AS EMPLEADO
FROM EMPLEADO e
RIGHT JOIN CARGO c
ON e.ID_CARGO = c.ID_CARGO
WHERE c.DESCRIPCION = 'Soporte Técnico'
GO

-- 5 EJEMPLOS FULL JOIN
SELECT e.ID_EMPLEADO, e.NOMBRE, c.DESCRIPCION AS CARGO
FROM EMPLEADO e
FULL JOIN CARGO c
ON e.ID_CARGO = c.ID_CARGO
GO

SELECT p.ID_PRODUCTO, p.NOMBRE_PRODUCTO, c.NOMBRE_CATEGORIA
FROM PRODUCTO p
FULL JOIN CATEGORIA c
ON p.ID_CATEGORIA = c.ID_CATEGORIA
GO

SELECT cl.ID_CLIENTE, cl.NOMBRE AS CLIENTE, cat.NOMBRE_CATEGORIA
FROM CLIENTE cl
FULL JOIN CATEGORIA cat
ON cl.HISTORIAL_COMPRA = 'Producto O, Producto P'
GO

SELECT e.ID_EMPLEADO, e.NOMBRE AS EMPLEADO, c.ID_CLIENTE, c.NOMBRE AS CLIENTE
FROM EMPLEADO e
FULL JOIN CLIENTE c
ON e.APELLIDOS = c.APELLIDOS
GO

SELECT p.ID_PRODUCTO, p.NOMBRE_PRODUCTO, c.NOMBRE_CATEGORIA
FROM PRODUCTO p
FULL JOIN CATEGORIA c
ON p.ID_CATEGORIA = c.ID_CATEGORIA
WHERE p.PRECIO_UNITARIO > 50
GO

--5 EJEMPLOS DE CONSULTAS
SELECT *
FROM EMPLEADO
GO

SELECT *
FROM CLIENTE
GO

SELECT *
FROM CARGO
GO

SELECT *
FROM PEDIDO
WHERE ID_PEDIDO <5
GO

SELECT *
FROM PEDIDO
WHERE FECHA_PEDIDO = '2023-03-01'
GO

--5 EJEMPLOS DE SUBCONSULTAS
SELECT NOMBRE,APELLIDOS
FROM CLIENTE
WHERE ID_CLIENTE IN (SELECT ID_CLIENTE 
FROM VENTA
WHERE TOTAL >1)
GO

SELECT NOMBRE_PROVEEDOR
FROM PROVEEDOR
WHERE ID_PROVEEDOR IN (
SELECT ID_PROVEEDOR
FROM ORDEN_COMPRA
WHERE ID_ORDEN_COMPRA IN (
SELECT ID_LOTE
FROM LOTE
WHERE TOTAL_ORDEN > 50
)
)
GO

SELECT p.NOMBRE_PRODUCTO
FROM PRODUCTO p
WHERE p.ID_PRODUCTO IN (
SELECT pr.ID_PRODUCTO
FROM PROMOCION pr
WHERE pr.TIPO = 'Descuento'
)
GO

SELECT e.NOMBRE, e.APELLIDOS, 
(SELECT SUM(v.TOTAL) 
FROM VENTA v
WHERE v.ID_EMPLEADO = e.ID_EMPLEADO) AS TOTAL_VENDIDO
FROM EMPLEADO e;
GO

SELECT p.NOMBRE_PRODUCTO
FROM PRODUCTO p
WHERE p.ID_PRODUCTO IN (
SELECT d.ID_PRODUCTO
FROM DEVOLUCION d
)
GO

--5 EJEMPLOS DE ROLES
--ROL DE SERVIDOR
USE master
GO
CREATE LOGIN THEYLOR WITH PASSWORD = '123456'
GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER THEYLOR;
GO

USE master
GO
CREATE LOGIN VANIA WITH PASSWORD = '789456'
GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER VANIA;
GO

USE master
GO
CREATE LOGIN CAMILA WITH PASSWORD = '159753'
GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER CAMILA;
GO

USE master
GO
CREATE LOGIN SILVANA WITH PASSWORD = '951753'
GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER SILVANA;
GO

USE master
GO
CREATE LOGIN YULIANA WITH PASSWORD = '123789'
GO
ALTER SERVER ROLE [dbcreator] ADD MEMBER YULIANA;
GO

--5 EJEMPLOS DE SECUENCIA DE BACKUPS
--Completo

BACKUP DATABASE IV
TO DISK = N'C:\Copias de Seguridad\Backups de IV.bak'
WITH NAME='BackuP completo'
GO 

--BACKUP DIFERENCIAL

BACKUP DATABASE IV
TO DISK = N'C:\Copias de Seguridad\Backups de IV.bak'
WITH NAME='BackupDiferencial',DIFFERENTIAL
GO 

-- BACKUP DE LOG DE TRANSACCIONES

BACKUP LOG IV
TO DISK = N'C:\Copias de Seguridad\Backups de IV.bak'
WITH NAME='Backup de log 1 de transacciones'

-- BACKUP DE LOG DE TRANSACCIONES

BACKUP LOG IV
TO DISK = N'C:\Copias de Seguridad\Backups de IV.bak'
WITH NAME='Backup de log 2 de transacciones'

-- BACKUP DE LOG DE TRANSACCIONES

BACKUP LOG IV
TO DISK = N'C:\Copias de Seguridad\Backups de IV.bak'
WITH NAME='Backup de log 3 de transacciones'

--SOLO PARA VISUALIZAR LO QUE HAY EN EL ARCHIVO . BAK

RESTORE HEADERONLY
FROM DISK = N'C:\Copias de Seguridad\Backups de IV.bak'

--elimanas la base de datos

DROP DATABASE  IV

--RESTAURO LA BASE DE DATOS 

RESTORE DATABASE IV FROM DISK = N'C:\Copias de Seguridad\Backups de IV.bak'
WITH FILE=1, NORECOVERY

--TODOS MENOS EL ULTIMO LLEVA NORECOVERY

RESTORE LOG AdventureWorks FROM DISK = N'C:\Copias de Seguridad\Backups de IV.bak'
WITH FILE=2,NORECOVERY

--AUN NO ESTA EN PRODUCCION

RESTORE LOG [AdventureWorks] FROM DISK = N'C:\Copias de Seguridad\Backups de IV.bak'
WITH FILE=3, NORECOVERY
RESTORE LOG [AdventureWorks] FROM DISK = N'C:\Copias de Seguridad\Backups de IV.bak'
WITH FILE=4, NORECOVERY
RESTORE LOG [AdventureWorks] FROM DISK = N'C:\Copias de Seguridad\Backups de IV.bak'
WITH FILE=5, RECOVERY

USE IV
GO

--Consultar la tabla cliente
SELECT * FROM CLIENTE
GO 
--LA BASE DE DATOS DEBE ESTAR EN FULL





















